
insert into state(id, name) values (nextval('hibernate_sequence'), 'Schleswig-Holstein');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Hamburg');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Niedersachsen');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Bremen');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Nordrhein-Westfalen');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Hessen');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Rheinland-Pfalz');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Baden-Württemberg');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Bayern');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Saarland');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Brandenburg');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Mecklenburg-Vorpommern');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Sachsen');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Sachsen-Anhalt');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Thüringen');
insert into state(id, name) values (nextval('hibernate_sequence'), 'Berlin');


insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Flensburg', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Kiel', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Lübeck', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Neumünster', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Dithmarschen', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Herzogtum Lauenburg', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Nordfriesland', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ostholstein', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Pinneberg', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Plön', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rendsburg-Eckernförde', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Schleswig-Flensburg', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Segeberg', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Steinburg', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Stormarn', 'Schleswig-Holstein');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Hamburg', 'Hamburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Braunschweig', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Salzgitter', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Wolfsburg', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Gifhorn', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Goslar', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Helmstedt', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Northeim', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Peine', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Wolfenbüttel', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Göttingen', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'Region Hannover', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Diepholz', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Hameln-Pyrmont', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Hildesheim', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Holzminden', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Nienburg (Weser)', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Schaumburg', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Celle', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Cuxhaven', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Harburg', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Lüchow-Dannenberg', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Lüneburg', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Osterholz', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rotenburg (Wümme)', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Heidekreis', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Stade', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Uelzen', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Verden', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Delmenhorst', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Emden', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Oldenburg', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Osnabrück', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Wilhelmshaven', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ammerland', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Aurich', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Cloppenburg', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Emsland', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Friesland', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Grafschaft Bentheim', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Leer', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Oldenburg', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Osnabrück', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Vechta', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Wesermarsch', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Wittmund', 'Niedersachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Bremen', 'Bremen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Bremerhaven', 'Bremen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Düsseldorf', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Duisburg', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Essen', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Krefeld', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Mönchengladbach', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Mülheim a.d.Ruhr', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Oberhausen', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Remscheid', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Solingen', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Wuppertal', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Kleve', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Mettmann', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rhein-Kreis Neuss', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Viersen', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Wesel', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Bonn', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Köln', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Leverkusen', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'StädteRegion Aachen', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Düren', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rhein-Erft-Kreis', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Euskirchen', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Heinsberg', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Oberbergischer Kreis', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rheinisch-Bergischer Kreis', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rhein-Sieg-Kreis', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Bottrop', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Gelsenkirchen', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Münster', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Borken', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Coesfeld', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Recklinghausen', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Steinfurt', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Warendorf', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Bielefeld', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Gütersloh', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Herford', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Höxter', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Lippe', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Minden-Lübbecke', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Paderborn', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Bochum', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Dortmund', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Hagen', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Hamm', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Herne', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ennepe-Ruhr-Kreis', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Hochsauerlandkreis', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Märkischer Kreis', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Olpe', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Siegen-Wittgenstein', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Soest', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Unna', 'Nordrhein-Westfalen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Darmstadt', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Frankfurt am Main', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Offenbach', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Wiesbaden', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bergstraße', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Darmstadt-Dieburg', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Groß-Gerau', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Hochtaunuskreis', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Main-Kinzig-Kreis', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Main-Taunus-Kreis', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Odenwaldkreis', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Offenbach', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rheingau-Taunus-Kreis', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Wetteraukreis', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Gießen', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Lahn-Dill-Kreis', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Limburg-Weilburg', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Marburg-Biedenkopf', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Vogelsbergkreis', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Kassel', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Fulda', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Hersfeld-Rotenburg', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Kassel', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Schwalm-Eder-Kreis', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Waldeck-Frankenberg', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Werra-Meißner-Kreis', 'Hessen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Koblenz', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ahrweiler', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Altenkirchen', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bad Kreuznach', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Birkenfeld', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Cochem-Zell', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Mayen-Koblenz', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Neuwied', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rhein-Hunsrück-Kreis', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rhein-Lahn-Kreis', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Westerwaldkreis', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Trier', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bernkastel-Wittlich', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bitburg-Prüm', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Vulkaneifel', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Trier-Saarburg', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Frankenthal', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Kaiserslautern', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Landau i.d.Pfalz', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Ludwigshafen', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Mainz', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Neustadt a.d.Weinstraße', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Pirmasens', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Speyer', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Worms', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Zweibrücken', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Alzey-Worms', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bad Dürkheim', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Donnersbergkreis', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Germersheim', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Kaiserslautern', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Kusel', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Südliche Weinstraße', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rhein-Pfalz-Kreis', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Mainz-Bingen', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Südwestpfalz', 'Rheinland-Pfalz');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Stuttgart', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Böblingen', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Esslingen', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Göppingen', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ludwigsburg', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rems-Murr-Kreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Heilbronn', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Heilbronn', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Hohenlohekreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Schwäbisch Hall', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Main-Tauber-Kreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Heidenheim', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ostalbkreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Baden-Baden', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Karlsruhe', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Karlsruhe', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rastatt', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Heidelberg', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Mannheim', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Neckar-Odenwald-Kreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rhein-Neckar-Kreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Pforzheim', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Calw', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Enzkreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Freudenstadt', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Freiburg i.Breisgau', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Breisgau-Hochschwarzwald', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Emmendingen', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ortenaukreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rottweil', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Schwarzwald-Baar-Kreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Tuttlingen', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Konstanz', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Lörrach', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Waldshut', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Reutlingen', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Tübingen', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Zollernalbkreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Ulm', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Alb-Donau-Kreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Biberach', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bodenseekreis', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ravensburg', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Sigmaringen', 'Baden-Württemberg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Ingolstadt', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK München', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Rosenheim', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Altötting', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Berchtesgadener Land', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bad Tölz-Wolfratshausen', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Dachau', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ebersberg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Eichstätt', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Erding', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Freising', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Fürstenfeldbruck', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Garmisch-Partenkirchen', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Landsberg a.Lech', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Miesbach', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Mühldorf a.Inn', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK München', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Neuburg-Schrobenhausen', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Pfaffenhofen a.d.Ilm', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rosenheim', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Starnberg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Traunstein', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Weilheim-Schongau', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Landshut', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Passau', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Straubing', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Deggendorf', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Freyung-Grafenau', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Kelheim', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Landshut', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Passau', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Regen', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rottal-Inn', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Straubing-Bogen', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Dingolfing-Landau', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Amberg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Regensburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Weiden i.d.OPf.', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Amberg-Sulzbach', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Cham', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Neumarkt i.d.OPf.', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Neustadt a.d.Waldnaab', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Regensburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Schwandorf', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Tirschenreuth', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Bamberg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Bayreuth', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Coburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Hof', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bamberg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bayreuth', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Coburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Forchheim', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Hof', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Kronach', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Kulmbach', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Lichtenfels', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Wunsiedel i.Fichtelgebirge', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Ansbach', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Erlangen', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Fürth', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Nürnberg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Schwabach', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ansbach', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Erlangen-Höchstadt', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Fürth', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Nürnberger Land', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Neustadt a.d.Aisch-Bad Windsheim', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Roth', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Weißenburg-Gunzenhausen', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Aschaffenburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Schweinfurt', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Würzburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Aschaffenburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bad Kissingen', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rhön-Grabfeld', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Haßberge', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Kitzingen', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Miltenberg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Main-Spessart', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Schweinfurt', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Würzburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Augsburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Kaufbeuren', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Kempten', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Memmingen', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Aichach-Friedberg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Augsburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Dillingen a.d.Donau', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Günzburg', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Neu-Ulm', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Lindau', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ostallgäu', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Unterallgäu', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Donau-Ries', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Oberallgäu', 'Bayern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Stadtverband Saarbrücken', 'Saarland');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Merzig-Wadern', 'Saarland');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Neunkirchen', 'Saarland');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Saarlouis', 'Saarland');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Saarpfalz-Kreis', 'Saarland');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Sankt Wendel', 'Saarland');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Brandenburg a.d.Havel', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Cottbus', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Frankfurt (Oder)', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Potsdam', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Barnim', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Dahme-Spreewald', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Elbe-Elster', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Havelland', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Märkisch-Oderland', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Oberhavel', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Oberspreewald-Lausitz', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Oder-Spree', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ostprignitz-Ruppin', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Potsdam-Mittelmark', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Prignitz', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Spree-Neiße', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Teltow-Fläming', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Uckermark', 'Brandenburg');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Rostock', 'Mecklenburg-Vorpommern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Schwerin', 'Mecklenburg-Vorpommern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Mecklenburgische Seenplatte', 'Mecklenburg-Vorpommern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Rostock', 'Mecklenburg-Vorpommern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Vorpommern-Rügen', 'Mecklenburg-Vorpommern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Nordwestmecklenburg', 'Mecklenburg-Vorpommern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Vorpommern-Greifswald', 'Mecklenburg-Vorpommern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ludwigslust-Parchim', 'Mecklenburg-Vorpommern');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Chemnitz', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Erzgebirgskreis', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Mittelsachsen', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Vogtlandkreis', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Zwickau', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Dresden', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Bautzen', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Görlitz', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Meißen', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Sächsische Schweiz-Osterzgebirge', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Leipzig', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Leipzig', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Nordsachsen', 'Sachsen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Dessau-Roßlau', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Halle', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Magdeburg', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Altmarkkreis Salzwedel', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Anhalt-Bitterfeld', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Börde', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Burgenlandkreis', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Harz', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Jerichower Land', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Mansfeld-Südharz', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Saalekreis', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Salzlandkreis', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Stendal', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Wittenberg', 'Sachsen-Anhalt');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Erfurt', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Gera', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Jena', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Suhl', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Weimar', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Eisenach', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Eichsfeld', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Nordhausen', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Wartburgkreis', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Unstrut-Hainich-Kreis', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Kyffhäuserkreis', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Schmalkalden-Meiningen', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Gotha', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Sömmerda', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Hildburghausen', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Ilm-Kreis', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Weimarer Land', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Sonneberg', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Saalfeld-Rudolstadt', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Saale-Holzland-Kreis', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Saale-Orla-Kreis', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Greiz', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'LK Altenburger Land', 'Thüringen');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Reinickendorf', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Charlottenburg-Wilmersdorf', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Treptow-Köpenick', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Pankow', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Neukölln', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Lichtenberg', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Marzahn-Hellersdorf', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Spandau', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Steglitz-Zehlendorf', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Mitte', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Friedrichshain-Kreuzberg', 'Berlin');
insert into county(id, name, state_name) values (nextval('hibernate_sequence'), 'SK Berlin Tempelhof-Schöneberg', 'Berlin');
